branch-defaults:
  dev:
    environment: staging
environment-defaults:
  staging:
    branch: dev
    repository: rails_latest_app
global:
  application_name: sample-demo-beanstalk
  branch: dev
  default_ec2_keyname: tween-dev-nvir
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: rails_latest_app
  sc: git
  workspace_type: Application
